### ISSUE TITLE
CollectionViewControllerDelegateのdidSupplementaryViewDequeued改修

### ISSUE THREAD

**Issue by akimatsui-cq** [miyoshi-cq/swift-architecture-template-ui#9]
CollectionViewControllerDelegateの `func didSupplementaryViewDequeued(:)` ではUICollectionReusableViewを渡していましたがPageControllerを使った場合など同一Collectionの同一UICollectionReusableViewが渡ってきたときCollectionの判定が行えない問題があった。
そのためdelegateメソッドを改修し、Collectionも渡す様にします。

```
// before
func didSupplementaryViewDequeued(supplementaryView: UICollectionReusableView?)

// after
func didSupplementaryViewDequeued<T: CollectionList>(collection: T, supplementaryView: UICollectionReusableView?)
```

**Comment by miyoshitakaaki** [comment]
@akimatsui-cq 
お願いします 🙏
